---
name: module3_task3

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    permissions:
      contents: write

    runs-on: ubuntu-22.04

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Run bash script"
        run: cd module3_task3 && ./setup.sh

      - name: "Run make build"
        run: cd module3_task3 && make build

      - name: "Testing"
        run: |
          cd module3_task3 && make validate
          make integration-tests
          make unit-tests
          make package
          make clean

      - name: Release
        env:
          TOKEN: ${{ secrets.TOKEN }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: 1.0.0
          files: |
            module3_task3/awesome-website.zip
            module3_task3/DEPLOY.md

      - name: "archive build"
        uses: actions/upload-artifact@v3
        with:
          name: "upload package"
          path: module3_task3/awesome-website.zip
